services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    environment:
      - DATABASE_NAME=${MONGO_INITDB_DATABASE}
      - MONGODB_HOST=${MONGODB_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - NODE_ENV=development
      - DOCKER_CONTAINER=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      mongodb:
        condition: service_started
      keycloak:
        condition: service_started
    mem_limit: 2g
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  mongodb:
    container_name: mongodbPFE
    image: mongo:latest
    ports:
      - "${DATABASE_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./backend/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    networks:
      - app-network

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - elasticsearch_data:/usr/share/elasticsearch/data

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.12.0
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
      - KC_CACHE_THEMES=false   
      - KC_CACHE_TEMPLATES=false
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm.json
      - KC_HOSTNAME_URL=${KEYCLOAK_URL}
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_PORT=${KEYCLOAK_PORT}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./myKeycloakTheme/myTheme:/opt/keycloak/themes/myTheme
      - ./myKeycloakTheme/realmSettings/realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - app-network
networks:
  app-network:
    name : mine-network
    driver: bridge

volumes:
  mongodb_data:
  # elasticsearch_data: